project:
  type: website
  output-dir: docs

website:
  title: "Black Educational Achievement Movement - Summer Camp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: presentation_july12th.qmd
        text: BEAM workshop
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

